---
- name: Desplegar PrestaShop en frontend master
  hosts: frontend_master
  become: true
  vars_files:
    - ../vars/variables.yaml
  tasks:

    - name: Descargar archivo de PrestaShop
      get_url:
        url: "https://github.com/PrestaShop/PrestaShop/releases/download/1.7.7.8/prestashop_1.7.7.8.zip"
        dest: "/tmp/prestashop.zip"

    - name: Descomprimir PrestaShop
      unarchive:
        src: /tmp/prestashop.zip
        dest: /var/www/html
        remote_src: yes

    - name: Configurar permisos para PrestaShop
      file:
        path: "{{ web_root }}"
        state: directory
        recurse: yes
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Habilitar módulo de reescritura de Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Habilitar el sitio PrestaShop en Apache
      command: a2ensite 000-default.conf
      notify: Reiniciar Apache

    - name: Asegurar permisos correctos para el frontend
      command: chown -R www-data:www-data {{ web_root }}

  handlers:
    - name: Reiniciar Apache
      systemd:
        name: apache2
        state: restarted
