---
- name: Instalar LAMP en backend
  hosts: backend
  become: true
  vars_files:
    - ../vars/variables.yaml
  tasks:
    - name: Añadir repositorio de PHP
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar dependencias necesarias
      apt:
        name:
          - apache2
          - php7.4
          - libapache2-mod-php7.4
          - php7.4-mysql
          - mariadb-server
          - python3-pymysql
        state: present

    - name: Iniciar y habilitar servicios
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - apache2
        - mariadb

    - name: Borrar base de datos PrestaShop si existe
      mysql_db:
        name: "{{ prestashop_db_name }}"
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Crear base de datos PrestaShop
      mysql_db:
        name: "{{ prestashop_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Crear usuario de base de datos
      mysql_user:
        name: "{{ prestashop_db_user }}"
        password: "{{ prestashop_db_password }}"
        priv: "{{ prestashop_db_name }}.*:ALL"
        host: '%'
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Permitir acceso remoto a MariaDB
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'

    - name: Reiniciar MariaDB
      systemd:
        name: mariadb
        state: restarted