---
- name: Instalar LAMP en frontend
  hosts: frontend
  become: true
  vars_files:
    - ../vars/variables.yaml  # Cargar variables
  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Añadir repositorio de PHP
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: Instalar Apache y PHP
      apt:
        name:
          - apache2
          - php7.4
          - libapache2-mod-php7.4
          - php7.4-mysql
          - php7.4-zip
          - unzip
          - php7.4-xml
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
        state: present

    - name: Iniciar y habilitar Apache
      systemd:
        name: apache2
        enabled: true
        state: started
